import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Heart, Leaf, Users } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { buttonVariants } from "@/components/ui/button";
import heroImage from "@/assets/mara-camp.jpg";
import detailImage from "@/assets/cc-safari-hero.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "About C&C Tour Company | Local Insight, Personal Journeys" }, { name: "description", content: "Meet C&C Tour Company and discover our thoughtful approach to private East African travel." }, { property: "og:title", content: "About C&C Tour Company" }, { property: "og:description", content: "Local insight, personal journeys and a lighter way to travel." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/about" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });

function AboutPage() { return <main><PageHero eyebrow="About C&C" title="Travel with people who know the way." intro="We believe the best journeys feel personal, unhurried and deeply connected to place." image={heroImage}/><section className="section-space mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow text-primary">Our story</p><h2 className="section-title mt-4">Born from a love of this land.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">C&C Tour Company is an independent travel studio creating memorable journeys across Kenya and East Africa. Our approach is simple: listen carefully, plan thoughtfully and leave room for the unexpected.</p><Link to="/contact" className={buttonVariants({ size: "xl", className: "mt-8" })}>Talk to our team <ArrowRight/></Link></div><img src={detailImage} alt="Travelers on safari in Kenya" loading="lazy" width={1920} height={1088} className="aspect-[4/5] w-full object-cover"/></div></section><section className="bg-secondary"><div className="section-space mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="eyebrow text-primary">What guides us</p><h2 className="section-title mt-4">Good travel should do good.</h2></div><div className="mt-12 grid gap-px bg-border md:grid-cols-3">{[{icon: Users,title:'People first',text:'Local guides, hosts and communities are at the heart of every journey.'},{icon: Leaf,title:'Tread lightly',text:'We favour smaller camps and experiences that respect the wild.'},{icon: Heart,title:'Care in every detail',text:'From first conversation to final farewell, we stay close at hand.'}].map(({icon: Icon,title,text}) => <article className="bg-secondary p-8 lg:p-10" key={title}><Icon className="h-8 w-8 text-primary" strokeWidth={1.4}/><h3 className="mt-8 font-display text-2xl">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section></main>; }