import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { buttonVariants } from "@/components/ui/button";
import { safariStyles } from "@/lib/travel-content";
import heroImage from "@/assets/south-luangwa-leopard.jpg";

export const Route = createFileRoute("/experiences")({ head: () => ({ meta: [{ title: "Safari Experiences | C&C Tour Company" }, { name: "description", content: "Explore classic safaris, family adventures, conservation travel and bush-and-beach experiences across Africa." }, { property: "og:title", content: "Safari Experiences | C&C Tour Company" }, { property: "og:description", content: "Choose how you want to experience Africa, from walking safaris to private family journeys." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/experiences" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/experiences" }] }), component: ExperiencesPage });

function ExperiencesPage() { return <main><PageHero eyebrow="Ways to travel" title="Experience Africa your way." intro="Begin with what moves you. We’ll connect the right places, people and pace around it." image={heroImage}/><section className="section-space mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-px border border-border bg-border md:grid-cols-2">{safariStyles.map((style) => <article key={style.name} className="group bg-background"><div className="aspect-[16/10] overflow-hidden"><img src={style.image} alt={style.name} loading="lazy" width={1600} height={1072} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-7 sm:p-10"><h2 className="font-display text-4xl">{style.name}</h2><p className="mt-3 max-w-lg leading-7 text-muted-foreground">{style.detail}</p><Link to="/tours" className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary">Explore sample tours <ArrowRight className="h-4 w-4"/></Link></div></article>)}</div><div className="mt-16 text-center"><Link to="/contact" className={buttonVariants({ size: "xl" })}>Create my experience <ArrowRight/></Link></div></section></main>; }