import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Clock, MapPin } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { buttonVariants } from "@/components/ui/button";
import heroImage from "@/assets/amboseli-elephants.jpg";
import maraImage from "@/assets/mara-camp.jpg";
import dianiImage from "@/assets/diani-dhow.jpg";
import safariImage from "@/assets/cc-safari-hero.jpg";

export const Route = createFileRoute("/tours")({ head: () => ({ meta: [{ title: "Safari & Beach Tours | C&C Tour Company" }, { name: "description", content: "Browse sample C&C Tour Company itineraries across Kenya, from Maasai Mara safaris to Diani beach escapes." }, { property: "og:title", content: "Safari & Beach Tours | C&C Tour Company" }, { property: "og:description", content: "Browse curated East African safari and coastal itineraries." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/tours" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/tours" }] }), component: ToursPage });

const tours = [{ title: "Mara Under Open Skies", type: "Signature safari", place: "Maasai Mara", days: "5 days", price: "$1,850", image: maraImage, text: "Big-cat country, intimate camps and golden-hour game drives." }, { title: "Giants of Amboseli", type: "Wildlife escape", place: "Amboseli", days: "4 days", price: "$1,420", image: heroImage, text: "Elephant herds and magnificent Kilimanjaro views." }, { title: "Coast & Dhow Escape", type: "Beach retreat", place: "Diani", days: "6 days", price: "$1,190", image: dianiImage, text: "Barefoot days, coral gardens and a private sunset sail." }, { title: "The Kenya Grand Journey", type: "Classic circuit", place: "Kenya", days: "10 days", price: "$3,750", image: safariImage, text: "A sweeping journey from the highlands to the Mara plains." }];

function ToursPage() { return <main><PageHero eyebrow="Our journeys" title="Stories worth travelling for." intro="A considered collection of safari and coastal journeys. Each can be adapted around you." image={heroImage}/><section className="section-space mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-8 md:grid-cols-2">{tours.map((tour) => <article key={tour.title} className="group border-b border-border pb-8"><div className="aspect-[16/11] overflow-hidden"><img src={tour.image} alt={`${tour.title}, ${tour.place}`} loading="lazy" width={1200} height={912} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="pt-6"><p className="eyebrow text-primary">{tour.type}</p><h2 className="mt-3 font-display text-3xl sm:text-4xl">{tour.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{tour.text}</p><div className="mt-5 flex flex-wrap items-center gap-5 text-xs font-semibold uppercase tracking-[0.12em]"><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-primary"/>{tour.place}</span><span className="inline-flex items-center gap-2"><Clock className="h-4 w-4 text-primary"/>{tour.days}</span><span>From {tour.price}</span></div></div></article>)}</div><div className="mt-16 flex flex-col items-start justify-between gap-6 border-t border-border pt-10 sm:flex-row sm:items-center"><div><p className="eyebrow text-primary">Something different?</p><h2 className="mt-3 font-display text-3xl">We’ll design it around you.</h2></div><Link to="/contact" className={buttonVariants({ size: "xl" })}>Request a custom tour <ArrowRight/></Link></div></section></main>; }