import { Link } from "@tanstack/react-router";
import { ChevronDown, ChevronLeft, ChevronRight, Mail, Menu, Phone, Star, X } from "lucide-react";
import { useState } from "react";
import { Button, buttonVariants } from "@/components/ui/button";

const menuGroups = [
  { label: "Discover", items: [{ label: "All destinations", to: "/destinations" }, { label: "Kenya", to: "/destinations/$country", country: "kenya" }, { label: "Tanzania", to: "/destinations/$country", country: "tanzania" }, { label: "Zambia", to: "/destinations/$country", country: "zambia" }, { label: "Experiences", to: "/experiences" }, { label: "Blog", to: "/blog" }] },
  { label: "Journeys", items: [{ label: "All tours", to: "/tours" }, { label: "Safari styles", to: "/safari-styles" }, { label: "Photo gallery", to: "/gallery" }, { label: "Guest reviews", to: "/reviews" }] },
] as const;
const directLinks = [{ label: "About", to: "/about" }, { label: "Contact", to: "/contact" }] as const;
const footerLinks = [
  { label: "Home", to: "/" },
  { label: "Destinations", to: "/destinations" },
  { label: "Safari styles", to: "/safari-styles" },
  { label: "All tours", to: "/tours" },
  { label: "Photo gallery", to: "/gallery" },
  { label: "Guest reviews", to: "/reviews" },
  { label: "Experiences", to: "/experiences" },
  { label: "Blog", to: "/blog" },
  ...directLinks,
] as const;

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  const [mobileGroup, setMobileGroup] = useState<(typeof menuGroups)[number]["label"] | null>(null);
  const closeMobileMenu = () => { setOpen(false); setMobileGroup(null); };
  const toggleMobileMenu = () => {
    setOpen((value) => { if (value) setMobileGroup(null); return !value; });
  };
  return <>
    <div className="absolute inset-x-0 top-0 z-50 hidden border-b border-primary-foreground/20 text-primary-foreground lg:block"><div className="mx-auto flex h-9 max-w-7xl items-center justify-between px-8 text-[10px] font-medium uppercase tracking-[0.14em]"><span>Authentic East Africa · Private journeys</span><div className="flex gap-6"><span className="inline-flex items-center gap-2"><Phone className="h-3 w-3" /> +254 700 123 456</span><span className="inline-flex items-center gap-2"><Mail className="h-3 w-3" /> hello@cctours.example</span></div></div></div>
    <header className="absolute inset-x-0 top-0 z-50 border-b border-primary-foreground/20 text-primary-foreground lg:top-9"><div className="mx-auto flex h-24 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" aria-label="C&C Tour Company home" className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center border border-primary-foreground/40 font-display text-2xl italic">C</span><span><span className="block font-display text-xl uppercase">C&amp;C Tour Company</span><span className="mt-1 block text-[8px] font-semibold uppercase tracking-[0.28em] text-accent">Authentic East Africa</span></span></Link><nav aria-label="Main navigation" className="hidden items-center gap-7 lg:flex"><Link to="/" activeProps={{ className: "text-accent" }} className="text-[10px] font-semibold uppercase tracking-[0.18em] hover:text-accent">Home</Link>{menuGroups.map((group) => <div key={group.label} className="group relative"><button type="button" className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-[0.18em] hover:text-accent" aria-haspopup="true">{group.label}<ChevronDown className="h-3 w-3" /></button><div className="invisible absolute left-1/2 top-full w-56 -translate-x-1/2 pt-5 opacity-0 transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><div className="border-t-2 border-accent bg-background p-2 text-foreground shadow-xl">{group.items.map((item) => "country" in item ? <Link key={item.label} to="/destinations/$country" params={{ country: item.country }} activeProps={{ className: "bg-secondary text-primary" }} className="block px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] hover:bg-secondary">{item.label}</Link> : <Link key={item.label} to={item.to} activeProps={{ className: "bg-secondary text-primary" }} className="block px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] hover:bg-secondary">{item.label}</Link>)}</div></div></div>)}{directLinks.map((item) => <Link key={item.to} to={item.to} activeProps={{ className: "text-accent" }} className="text-[10px] font-semibold uppercase tracking-[0.18em] hover:text-accent">{item.label}</Link>)}<Link to="/contact" className={buttonVariants({ variant: "light", size: "xl" })}>Plan a journey</Link></nav><Button aria-label={open ? "Close menu" : "Open menu"} variant="heroOutline" size="icon" className="lg:hidden" onClick={toggleMobileMenu}>{open ? <X /> : <Menu />}</Button></div></header>
    {open && <div className="fixed inset-0 z-40 overflow-y-auto bg-foreground px-5 pb-8 pt-28 text-background lg:hidden">{mobileGroup === null ? <nav aria-label="Mobile navigation" className="flex flex-col border-t border-background/20"><Link to="/" onClick={closeMobileMenu} className="border-b border-background/20 py-5 font-display text-3xl">Home</Link>{menuGroups.map((group) => <Button key={group.label} type="button" variant="ghost" onClick={() => setMobileGroup(group.label)} className="h-auto justify-between rounded-none border-b border-background/20 px-0 py-5 font-display text-3xl font-normal text-background hover:bg-transparent hover:text-accent">{group.label}<ChevronRight className="size-6" /></Button>)}{directLinks.map((item) => <Link key={item.to} to={item.to} onClick={closeMobileMenu} className="border-b border-background/20 py-5 font-display text-3xl">{item.label}</Link>)}</nav> : <nav aria-label={`${mobileGroup} navigation`}><Button type="button" variant="ghost" onClick={() => setMobileGroup(null)} className="h-auto rounded-none px-0 py-3 text-sm text-accent hover:bg-transparent hover:text-accent"><ChevronLeft className="size-5" />Back</Button><h2 className="border-b border-background/20 pb-5 font-display text-4xl">{mobileGroup}</h2><div className="flex flex-col">{menuGroups.find((group) => group.label === mobileGroup)?.items.map((item) => "country" in item ? <Link key={item.label} to="/destinations/$country" params={{ country: item.country }} onClick={closeMobileMenu} className="border-b border-background/20 py-5 font-display text-2xl">{item.label}</Link> : <Link key={item.label} to={item.to} onClick={closeMobileMenu} className="border-b border-background/20 py-5 font-display text-2xl">{item.label}</Link>)}</div></nav>}<p className="mt-8 text-sm text-background/60">Private journeys across East Africa</p></div>}
  </>;
}

export function SiteFooter() {
  return <footer className="bg-foreground text-background"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-12 border-b border-background/20 pb-14 md:grid-cols-2 lg:grid-cols-4"><div><div className="font-display text-4xl">C&amp;C</div><p className="mt-4 max-w-xs text-sm leading-6 text-background/70">Considered journeys, meaningful encounters and East Africa at its most extraordinary.</p><div className="mt-7 flex gap-3"><a href="https://www.tripadvisor.com/" target="_blank" rel="noopener noreferrer" className="border border-background/25 px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.12em] hover:border-accent hover:text-accent">Tripadvisor</a><a href="https://www.google.com/maps" target="_blank" rel="noopener noreferrer" className="border border-background/25 px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.12em] hover:border-accent hover:text-accent"><Star className="mr-1 inline h-3 w-3"/>Google Reviews</a></div></div><div><h2 className="eyebrow text-accent">Explore</h2><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{footerLinks.map((item) => <Link key={item.to} to={item.to} className="w-fit hover:text-accent">{item.label}</Link>)}</div></div><div><h2 className="eyebrow text-accent">Contact</h2><address className="mt-5 space-y-3 text-sm not-italic text-background/70"><p>Nairobi, Kenya</p><p>+254 700 123 456</p><p>hello@cctours.example</p></address></div><div><h2 className="eyebrow text-accent">Good to know</h2><p className="mt-5 text-sm leading-6 text-background/70">Tours, ratings, prices, contact details and review links are sample content ready for your updates.</p></div></div><div className="flex flex-col justify-between gap-3 pt-6 text-xs text-background/60 sm:flex-row"><p>© 2026 C&amp;C Tour Company.</p><p>Travel thoughtfully. Tread lightly.</p></div></div></footer>;
}