/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SafariStylesRouteImport } from './routes/safari-styles'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsCountryRouteImport } from './routes/destinations.$country'
import { Route as DestinationsCountryAreaRouteImport } from './routes/destinations.$country.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariStylesRoute = SafariStylesRouteImport.update({
  id: '/safari-styles',
  path: '/safari-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsCountryRoute = DestinationsCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => DestinationsRoute,
} as any)
const DestinationsCountryAreaRoute = DestinationsCountryAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => DestinationsCountryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/safari-styles': typeof SafariStylesRoute
  '/tours': typeof ToursRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$country/$area': typeof DestinationsCountryAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/safari-styles': typeof SafariStylesRoute
  '/tours': typeof ToursRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/$country/$area': typeof DestinationsCountryAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/safari-styles': typeof SafariStylesRoute
  '/tours': typeof ToursRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$country/$area': typeof DestinationsCountryAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/gallery'
    | '/reviews'
    | '/safari-styles'
    | '/tours'
    | '/destinations/$country'
    | '/destinations/'
    | '/destinations/$country/$area'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/reviews'
    | '/safari-styles'
    | '/tours'
    | '/destinations/$country'
    | '/destinations'
    | '/destinations/$country/$area'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/gallery'
    | '/reviews'
    | '/safari-styles'
    | '/tours'
    | '/destinations/$country'
    | '/destinations/'
    | '/destinations/$country/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  SafariStylesRoute: typeof SafariStylesRoute
  ToursRoute: typeof ToursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-styles': {
      id: '/safari-styles'
      path: '/safari-styles'
      fullPath: '/safari-styles'
      preLoaderRoute: typeof SafariStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/$country': {
      id: '/destinations/$country'
      path: '/$country'
      fullPath: '/destinations/$country'
      preLoaderRoute: typeof DestinationsCountryRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/destinations/$country/$area': {
      id: '/destinations/$country/$area'
      path: '/$area'
      fullPath: '/destinations/$country/$area'
      preLoaderRoute: typeof DestinationsCountryAreaRouteImport
      parentRoute: typeof DestinationsCountryRoute
    }
  }
}

interface DestinationsCountryRouteChildren {
  DestinationsCountryAreaRoute: typeof DestinationsCountryAreaRoute
}

const DestinationsCountryRouteChildren: DestinationsCountryRouteChildren = {
  DestinationsCountryAreaRoute: DestinationsCountryAreaRoute,
}

const DestinationsCountryRouteWithChildren =
  DestinationsCountryRoute._addFileChildren(DestinationsCountryRouteChildren)

interface DestinationsRouteChildren {
  DestinationsCountryRoute: typeof DestinationsCountryRouteWithChildren
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsCountryRoute: DestinationsCountryRouteWithChildren,
  DestinationsIndexRoute: DestinationsIndexRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  SafariStylesRoute: SafariStylesRoute,
  ToursRoute: ToursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
